<?php
return [
        'label'       => 'Antrean RS',
        'icon'        => '🩺',
        'description' => 'Modul Antrean Rumah Sakit',
        'base_url'    => getBaseUrl('antrean_rs', $currentDomain, $isDevMode),
        'sub_modules' => [
            // WS BPJS Endpoints (diakses oleh RS)
            [
                'key'         => 'ref_poli',
                'label'       => 'Referensi Poli',
                'method'      => 'GET',
                'path'        => '/ref/poli',
                'description' => 'Melihat referensi poli yang ada pada Aplikasi HFIS',
                'params'      => [],
            ],
            [
                'key'         => 'ref_dokter',
                'label'       => 'Referensi Dokter',
                'method'      => 'GET',
                'path'        => '/ref/dokter',
                'description' => 'Melihat referensi dokter yang ada pada Aplikasi HFIS',
                'params'      => [],
            ],
            [
                'key'         => 'jadwal_dokter',
                'label'       => 'Referensi Jadwal Dokter',
                'method'      => 'GET',
                'path'        => '/jadwaldokter/kodepoli/{kodepoli}/tanggal/{tanggal}',
                'description' => 'Melihat referensi jadwal dokter yang ada pada Aplikasi HFIS',
                'params'      => [
                    ['name' => 'kodepoli', 'type' => 'text', 'placeholder' => 'Kode Poli (misal: ANA)', 'default' => ''],
                    ['name' => 'tanggal', 'type' => 'text', 'placeholder' => 'Tanggal (YYYY-MM-DD)', 'default' => date('Y-m-d')],
                ],
            ],
            [
                'key'         => 'ref_poli_fp',
                'label'       => 'Referensi Poli Finger Print',
                'method'      => 'GET',
                'path'        => '/ref/poli/fp',
                'description' => 'Melihat referensi poli finger print',
                'params'      => [],
            ],
            [
                'key'         => 'ref_pasien_fp',
                'label'       => 'Referensi Pasien Finger Print',
                'method'      => 'GET',
                'path'        => '/ref/pasien/fp/identitas/{nik}/noidentitas/{noidentitas}',
                'description' => 'Melihat referensi pasien finger print',
                'params'      => [
                    ['name' => 'nik', 'type' => 'text', 'placeholder' => 'NIK', 'default' => ''],
                    ['name' => 'noidentitas', 'type' => 'text', 'placeholder' => 'No Identitas', 'default' => ''],
                ],
            ],
            [
                'key'         => 'update_jadwal_dokter',
                'label'       => 'Update Jadwal Dokter',
                'method'      => 'POST',
                'path'        => '/jadwaldokter/updatejadwaldokter',
                'description' => 'Update jadwal dokter yang ada pada Aplikasi HFIS',
                'body'        => [
                    ['name' => 'kodepoli', 'type' => 'text', 'placeholder' => 'Kode Poli BPJS', 'default' => ''],
                    ['name' => 'kodesubspesialis', 'type' => 'text', 'placeholder' => 'Kode Subspesialis BPJS', 'default' => ''],
                    ['name' => 'kodedokter', 'type' => 'number', 'placeholder' => 'Kode Dokter BPJS', 'default' => ''],
                    ['name' => 'jadwal', 'type' => 'json', 'placeholder' => 'Array jadwal', 'default' => ''],
                ],
            ],
            [
                'key'         => 'tambah_antrean',
                'label'       => 'Tambah Antrean',
                'method'      => 'POST',
                'path'        => '/antrean/add',
                'description' => 'Menambah Antrean RS',
                'body'        => [
                    ['name' => 'kodebooking', 'type' => 'text', 'placeholder' => 'Kode Booking Unik', 'default' => ''],
                    ['name' => 'jenispasien', 'type' => 'text', 'placeholder' => 'JKN / NON JKN', 'default' => 'JKN'],
                    ['name' => 'nomorkartu', 'type' => 'text', 'placeholder' => 'No Kartu BPJS (kosongkan jika NON JKN)', 'default' => ''],
                    ['name' => 'nik', 'type' => 'text', 'placeholder' => 'NIK Pasien', 'default' => ''],
                    ['name' => 'nohp', 'type' => 'text', 'placeholder' => 'No HP Pasien', 'default' => ''],
                    ['name' => 'kodepoli', 'type' => 'text', 'placeholder' => 'Kode Subspesialis BPJS', 'default' => ''],
                    ['name' => 'namapoli', 'type' => 'text', 'placeholder' => 'Nama Poli', 'default' => ''],
                    ['name' => 'pasienbaru', 'type' => 'number', 'placeholder' => '1 (Ya) / 0 (Tidak)', 'default' => '1'],
                    ['name' => 'norm', 'type' => 'text', 'placeholder' => 'No Rekam Medis', 'default' => ''],
                    ['name' => 'tanggalperiksa', 'type' => 'text', 'placeholder' => 'Tanggal Periksa (YYYY-MM-DD)', 'default' => date('Y-m-d')],
                    ['name' => 'kodedokter', 'type' => 'number', 'placeholder' => 'Kode Dokter BPJS', 'default' => ''],
                    ['name' => 'namadokter', 'type' => 'text', 'placeholder' => 'Nama Dokter', 'default' => ''],
                    ['name' => 'jampraktek', 'type' => 'text', 'placeholder' => 'Jam Praktek Dokter', 'default' => ''],
                    ['name' => 'jeniskunjungan', 'type' => 'number', 'placeholder' => '1 (Rujukan FKTP), 2 (Rujukan Internal), 3 (Kontrol), 4 (Rujukan Antar RS)', 'default' => '1'],
                    ['name' => 'nomorreferensi', 'type' => 'text', 'placeholder' => 'No Rujukan/Kontrol JKN', 'default' => ''],
                    ['name' => 'nomorantrean', 'type' => 'text', 'placeholder' => 'Nomor Antrean', 'default' => ''],
                    ['name' => 'angkaantrean', 'type' => 'number', 'placeholder' => 'Angka Antrean', 'default' => '1'],
                    ['name' => 'estimasidilayani', 'type' => 'number', 'placeholder' => 'Estimasi Dilayani (milliseconds)', 'default' => ''],
                    ['name' => 'sisakuotajkn', 'type' => 'number', 'placeholder' => 'Sisa Kuota JKN', 'default' => ''],
                    ['name' => 'kuotajkn', 'type' => 'number', 'placeholder' => 'Kuota JKN', 'default' => ''],
                    ['name' => 'sisakuotanonjkn', 'type' => 'number', 'placeholder' => 'Sisa Kuota Non JKN', 'default' => ''],
                    ['name' => 'kuotanonjkn', 'type' => 'number', 'placeholder' => 'Kuota Non JKN', 'default' => ''],
                    ['name' => 'keterangan', 'type' => 'text', 'placeholder' => 'Informasi untuk Pasien', 'default' => ''],
                ],
            ],
            [
                'key'         => 'tambah_antrean_farmasi',
                'label'       => 'Tambah Antrean Farmasi',
                'method'      => 'POST',
                'path'        => '/antrean/farmasi/add',
                'description' => 'Menambah Antrean Farmasi RS',
                'body'        => [
                    ['name' => 'kodebooking', 'type' => 'text', 'placeholder' => 'Kode Booking', 'default' => ''],
                    ['name' => 'jenisresep', 'type' => 'text', 'placeholder' => 'racikan / non racikan', 'default' => 'racikan'],
                    ['name' => 'nomorantrean', 'type' => 'number', 'placeholder' => 'Nomor Antrean', 'default' => '1'],
                    ['name' => 'keterangan', 'type' => 'text', 'placeholder' => 'Keterangan', 'default' => ''],
                ],
            ],
            [
                'key'         => 'update_waktu_antrean',
                'label'       => 'Update Waktu Antrean',
                'method'      => 'POST',
                'path'        => '/antrean/updatewaktu',
                'description' => 'Mengirimkan waktu tunggu/waktu layan',
                'body'        => [
                    ['name' => 'kodebooking', 'type' => 'text', 'placeholder' => 'Kode Booking', 'default' => ''],
                    ['name' => 'taskid', 'type' => 'number', 'placeholder' => '1-99 (lihat catatan di dokumentasi)', 'default' => '1'],
                    ['name' => 'waktu', 'type' => 'number', 'placeholder' => 'Waktu dalam milliseconds', 'default' => ''],
                ],
            ],
            [
                'key'         => 'batal_antrean',
                'label'       => 'Batal Antrean',
                'method'      => 'POST',
                'path'        => '/antrean/batal',
                'description' => 'Membatalkan antrean pasien',
                'body'        => [
                    ['name' => 'kodebooking', 'type' => 'text', 'placeholder' => 'Kode Booking', 'default' => ''],
                    ['name' => 'keterangan', 'type' => 'text', 'placeholder' => 'Alasan Pembatalan', 'default' => ''],
                ],
            ],
            [
                'key'         => 'list_waktu_task',
                'label'       => 'List Waktu Task Id',
                'method'      => 'POST',
                'path'        => '/antrean/getlisttask',
                'description' => 'Meliat waktu task id yang telah dikirim ke BPJS',
                'body'        => [
                    ['name' => 'kodebooking', 'type' => 'text', 'placeholder' => 'Kode Booking', 'default' => ''],
                ],
            ],
            [
                'key'         => 'dashboard_per_tanggal',
                'label'       => 'Dashboard Per Tanggal',
                'method'      => 'GET',
                'path'        => '/dashboard/waktutunggu/tanggal/{tanggal}/waktu/{waktu}',
                'description' => 'Dashboard waktu per tanggal',
                'params'      => [
                    ['name' => 'tanggal', 'type' => 'text', 'placeholder' => 'Tanggal (YYYY-MM-DD)', 'default' => date('Y-m-d')],
                    ['name' => 'waktu', 'type' => 'text', 'placeholder' => 'rs atau server', 'default' => 'rs'],
                ],
            ],
            [
                'key'         => 'dashboard_per_bulan',
                'label'       => 'Dashboard Per Bulan',
                'method'      => 'GET',
                'path'        => '/dashboard/waktutunggu/bulan/{bulan}/tahun/{tahun}/waktu/{waktu}',
                'description' => 'Dashboard waktu per bulan',
                'params'      => [
                    ['name' => 'bulan', 'type' => 'text', 'placeholder' => 'Bulan (01-12)', 'default' => ''],
                    ['name' => 'tahun', 'type' => 'text', 'placeholder' => 'Tahun (YYYY)', 'default' => ''],
                    ['name' => 'waktu', 'type' => 'text', 'placeholder' => 'rs atau server', 'default' => 'rs'],
                ],
            ],
            [
                'key'         => 'antrean_per_tanggal',
                'label'       => 'Antrean Per Tanggal',
                'method'      => 'GET',
                'path'        => '/antrean/pendaftaran/tanggal/{tanggal}',
                'description' => 'Meliat pendaftaran antrean per tanggal',
                'params'      => [
                    ['name' => 'tanggal', 'type' => 'text', 'placeholder' => 'Tanggal (YYYY-MM-DD)', 'default' => date('Y-m-d')],
                ],
            ],
            [
                'key'         => 'antrean_per_kode_booking',
                'label'       => 'Antrean Per Kode Booking',
                'method'      => 'GET',
                'path'        => '/antrean/pendaftaran/kodebooking/{kodebooking}',
                'description' => 'Meliat pendaftaran antrean per kode booking',
                'params'      => [
                    ['name' => 'kodebooking', 'type' => 'text', 'placeholder' => 'Kode Booking', 'default' => ''],
                ],
            ],
            [
                'key'         => 'antrean_belum_dilayani',
                'label'       => 'Antrean Belum Dilayani',
                'method'      => 'GET',
                'path'        => '/antrean/pendaftaran/aktif',
                'description' => 'Meliat pendaftaran antrean belum dilayani',
                'params'      => [],
            ],
            [
                'key'         => 'antrean_belum_dilayani_detail',
                'label'       => 'Antrean Belum Dilayani Detail',
                'method'      => 'GET',
                'path'        => '/antrean/pendaftaran/kodepoli/{kodepoli}/kodedokter/{kodedokter}/hari/{hari}/jampraktek/{jampraktek}',
                'description' => 'Meliat pendaftaran antrean belum dilayani per poli per dokter per hari per jam praktek',
                'params'      => [
                    ['name' => 'kodepoli', 'type' => 'text', 'placeholder' => 'Kode Poli', 'default' => ''],
                    ['name' => 'kodedokter', 'type' => 'number', 'placeholder' => 'Kode Dokter', 'default' => ''],
                    ['name' => 'hari', 'type' => 'number', 'placeholder' => '1-8 (1=Mon, 2=Tue, ..., 8=National Holiday)', 'default' => ''],
                    ['name' => 'jampraktek', 'type' => 'text', 'placeholder' => 'Jam Praktek', 'default' => ''],
                ],
            ],
            // WS RS Endpoints (diakses oleh Mobile JKN)
            [
                'key'         => 'token_rs',
                'label'       => 'Token',
                'method'      => 'GET',
                'path'        => '/rs/token',
                'description' => 'Membuat token',
                'headers'     => ['x-username', 'x-password'],
            ],
            [
                'key'         => 'status_antrean_rs',
                'label'       => 'Status Antrean',
                'method'      => 'POST',
                'path'        => '/rs/status',
                'description' => 'Menampilkan status antrean per poli (untuk perencanaan kedatangan pasien)',
                'body'        => [
                    ['name' => 'kodepoli', 'type' => 'text', 'placeholder' => 'Kode Subspesialis BPJS', 'default' => ''],
                    ['name' => 'kodedokter', 'type' => 'number', 'placeholder' => 'Kode Dokter BPJS', 'default' => ''],
                    ['name' => 'tanggalperiksa', 'type' => 'text', 'placeholder' => 'Tanggal Rencana Berobat (YYYY-MM-DD)', 'default' => ''],
                    ['name' => 'jampraktek', 'type' => 'text', 'placeholder' => 'Jam Praktek Dokter', 'default' => ''],
                ],
            ],
            [
                'key'         => 'ambil_antrean_rs',
                'label'       => 'Ambil Antrean',
                'method'      => 'POST',
                'path'        => '/rs/antrean',
                'description' => 'Mengambil antrean',
                'body'        => [
                    ['name' => 'nomorkartu', 'type' => 'text', 'placeholder' => 'No Kartu BPJS (kosongkan jika NON JKN)', 'default' => ''],
                    ['name' => 'nik', 'type' => 'text', 'placeholder' => 'NIK Pasien', 'default' => ''],
                    ['name' => 'nohp', 'type' => 'text', 'placeholder' => 'No HP Pasien', 'default' => ''],
                    ['name' => 'kodepoli', 'type' => 'text', 'placeholder' => 'Kode Subspesialis BPJS', 'default' => ''],
                    ['name' => 'norm', 'type' => 'text', 'placeholder' => 'No Rekam Medis', 'default' => ''],
                    ['name' => 'tanggalperiksa', 'type' => 'text', 'placeholder' => 'Tanggal Periksa (YYYY-MM-DD)', 'default' => date('Y-m-d')],
                    ['name' => 'kodedokter', 'type' => 'number', 'placeholder' => 'Kode Dokter BPJS', 'default' => ''],
                    ['name' => 'jampraktek', 'type' => 'text', 'placeholder' => 'Jam Praktek', 'default' => ''],
                    ['name' => 'jeniskunjungan', 'type' => 'number', 'placeholder' => '1-4', 'default' => '1'],
                    ['name' => 'nomorreferensi', 'type' => 'text', 'placeholder' => 'No Rujukan (kosongkan jika NON JKN)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sisa_antrean_rs',
                'label'       => 'Sisa Antrean',
                'method'      => 'POST',
                'path'        => '/rs/sisaantrean',
                'description' => 'Meliat sisa antrean di hari H pelayanan',
                'body'        => [
                    ['name' => 'kodebooking', 'type' => 'text', 'placeholder' => 'Kode Booking', 'default' => ''],
                ],
            ],
            [
                'key'         => 'batal_antrean_rs',
                'label'       => 'Batal Antrean',
                'method'      => 'POST',
                'path'        => '/rs/batal',
                'description' => 'Membatalkan antrean pasien',
                'body'        => [
                    ['name' => 'kodebooking', 'type' => 'text', 'placeholder' => 'Kode Booking', 'default' => ''],
                    ['name' => 'keterangan', 'type' => 'text', 'placeholder' => 'Alasan Pembatalan', 'default' => ''],
                ],
            ],
            [
                'key'         => 'checkin_antrean_rs',
                'label'       => 'Check In',
                'method'      => 'POST',
                'path'        => '/rs/checkin',
                'description' => 'Memastikan pasien sudah datang di RS',
                'body'        => [
                    ['name' => 'kodebooking', 'type' => 'text', 'placeholder' => 'Kode Booking', 'default' => ''],
                    ['name' => 'waktu', 'type' => 'number', 'placeholder' => 'Waktu Check-in (milliseconds)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'info_pasien_baru_rs',
                'label'       => 'Info Pasien Baru',
                'method'      => 'POST',
                'path'        => '/rs/pasienbaru',
                'description' => 'Informasi identitas pasien baru yang belum punya rekam medis',
                'body'        => [
                    ['name' => 'nomorkartu', 'type' => 'text', 'placeholder' => 'No Kartu Pasien JKN', 'default' => ''],
                    ['name' => 'nik', 'type' => 'text', 'placeholder' => 'NIK Pasien', 'default' => ''],
                    ['name' => 'nomorkk', 'type' => 'text', 'placeholder' => 'No KK Pasien', 'default' => ''],
                    ['name' => 'nama', 'type' => 'text', 'placeholder' => 'Nama Pasien', 'default' => ''],
                    ['name' => 'jeniskelamin', 'type' => 'text', 'placeholder' => 'Jenis Kelamin', 'default' => ''],
                    ['name' => 'tanggallahir', 'type' => 'text', 'placeholder' => 'Tanggal Lahir (YYYY-MM-DD)', 'default' => ''],
                    ['name' => 'nohp', 'type' => 'text', 'placeholder' => 'No HP Pasien', 'default' => ''],
                    ['name' => 'alamat', 'type' => 'text', 'placeholder' => 'Alamat Pasien', 'default' => ''],
                    ['name' => 'kodeprop', 'type' => 'text', 'placeholder' => 'Kode Propinsi BPJS', 'default' => ''],
                    ['name' => 'namaprop', 'type' => 'text', 'placeholder' => 'Nama Propinsi', 'default' => ''],
                    ['name' => 'kodedati2', 'type' => 'text', 'placeholder' => 'Kode Kota/Kab BPJS', 'default' => ''],
                    ['name' => 'namadati2', 'type' => 'text', 'placeholder' => 'Nama Kota/Kab', 'default' => ''],
                    ['name' => 'kodekec', 'type' => 'text', 'placeholder' => 'Kode Kecamatan BPJS', 'default' => ''],
                    ['name' => 'namakec', 'type' => 'text', 'placeholder' => 'Nama Kecamatan', 'default' => ''],
                    ['name' => 'kodekel', 'type' => 'text', 'placeholder' => 'Kode Kelurahan BPJS', 'default' => ''],
                    ['name' => 'namakel', 'type' => 'text', 'placeholder' => 'Nama Kelurahan', 'default' => ''],
                    ['name' => 'rw', 'type' => 'text', 'placeholder' => 'No RT', 'default' => ''],
                    ['name' => 'rt', 'type' => 'text', 'placeholder' => 'No RW', 'default' => ''],
                ],
            ],
            [
                'key'         => 'jadwal_operasi_rs',
                'label'       => 'Jadwal Operasi RS',
                'method'      => 'POST',
                'path'        => '/rs/jadwaloperasi',
                'description' => 'Informasi jadwal operasi di rumah sakit',
                'body'        => [
                    ['name' => 'tanggalawal', 'type' => 'text', 'placeholder' => 'Tanggal Awal (YYYY-MM-DD)', 'default' => ''],
                    ['name' => 'tanggalakhir', 'type' => 'text', 'placeholder' => 'Tanggal Akhir (YYYY-MM-DD)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'jadwal_operasi_pasien_rs',
                'label'       => 'Jadwal Operasi Pasien',
                'method'      => 'POST',
                'path'        => '/rs/jadwaloperasipasien',
                'description' => 'Informasi jadwal operasi per pasien',
                'body'        => [
                    ['name' => 'nopeserta', 'type' => 'text', 'placeholder' => 'No Kartu Pasien JKN', 'default' => ''],
                ],
            ],
            [
                'key'         => 'ambil_antrean_farmasi_rs',
                'label'       => 'Ambil Antrean Farmasi',
                'method'      => 'POST',
                'path'        => '/rs/farmasi/ambil',
                'description' => 'Mengambil antrean farmasi',
                'body'        => [
                    ['name' => 'kodebooking', 'type' => 'text', 'placeholder' => 'Kode Booking', 'default' => ''],
                ],
            ],
            [
                'key'         => 'status_antrean_farmasi_rs',
                'label'       => 'Status Antrean Farmasi',
                'method'      => 'POST',
                'path'        => '/rs/farmasi/status',
                'description' => 'Mengetahui status antrean farmasi',
                'body'        => [
                    ['name' => 'kodebooking', 'type' => 'text', 'placeholder' => 'Kode Booking', 'default' => ''],
                ],
            ],
        ],
    ];