<?php
return [
        'label'       => 'Antrean FKTP',
        'icon'        => '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 12.414a8 8 0 11-3.536-3.536L8.343 7.657m8.484 8.484z"/></svg>',
        'description' => 'Modul Antrean Fasilitas Kesehatan Tingkat Pertama',
        'base_url'    => getBaseUrl('antrean_fktp', $currentDomain, $isDevMode),
        'sub_modules' => [
            // Token
            [
                'key'         => 'token_fktp',
                'label'       => 'Token',
                'method'      => 'GET',
                'path'        => '/auth',
                'description' => 'Membuat token akses - Header: x-username, x-password',
                'headers'     => ['x-username', 'x-password'],
            ],
            // Status Antrean
            [
                'key'         => 'status_antrean_fktp',
                'label'       => 'Status Antrean',
                'method'      => 'GET',
                'path'        => '/antrean/status/{kode_poli}/{tanggalperiksa}',
                'description' => 'Menampilkan status antrean per poli - Header: x-token, x-username',
                'params'      => [
                    ['name' => 'kode_poli', 'type' => 'text', 'placeholder' => 'Kode Poli (misal: 001)', 'default' => ''],
                    ['name' => 'tanggalperiksa', 'type' => 'text', 'placeholder' => 'Tanggal (YYYY-MM-DD)', 'default' => date('Y-m-d')],
                ],
                'headers'     => ['x-token', 'x-username'],
            ],
            // Ambil Antrean
            [
                'key'         => 'ambil_antrean_fktp',
                'label'       => 'Ambil Antrean',
                'method'      => 'POST',
                'path'        => '/antrean',
                'description' => 'Mengambil antrean - Header: x-token, x-username',
                'body'        => [
                    ['name' => 'nomorkartu', 'type' => 'text', 'placeholder' => 'No Kartu BPJS (kosongkan jika NON JKN)', 'default' => ''],
                    ['name' => 'nik', 'type' => 'text', 'placeholder' => 'NIK Pasien', 'default' => ''],
                    ['name' => 'nohp', 'type' => 'text', 'placeholder' => 'No HP Pasien', 'default' => ''],
                    ['name' => 'kodepoli', 'type' => 'text', 'placeholder' => 'Kode Poli', 'default' => ''],
                    ['name' => 'namapoli', 'type' => 'text', 'placeholder' => 'Nama Poli', 'default' => ''],
                    ['name' => 'norm', 'type' => 'text', 'placeholder' => 'No Rekam Medis', 'default' => ''],
                    ['name' => 'tanggalperiksa', 'type' => 'text', 'placeholder' => 'Tanggal Periksa (YYYY-MM-DD)', 'default' => date('Y-m-d')],
                    ['name' => 'kodedokter', 'type' => 'number', 'placeholder' => 'Kode Dokter', 'default' => ''],
                    ['name' => 'namadokter', 'type' => 'text', 'placeholder' => 'Nama Dokter', 'default' => ''],
                    ['name' => 'jampraktek', 'type' => 'text', 'placeholder' => 'Jam Praktek', 'default' => ''],
                    ['name' => 'nomorantrean', 'type' => 'text', 'placeholder' => 'Nomor Antrean', 'default' => ''],
                    ['name' => 'angkaantrean', 'type' => 'number', 'placeholder' => 'Angka Antrean', 'default' => ''],
                    ['name' => 'keterangan', 'type' => 'text', 'placeholder' => 'Keterangan', 'default' => ''],
                ],
                'headers'     => ['x-token', 'x-username'],
            ],
            // Sisa Antrean
            [
                'key'         => 'sisa_antrean_fktp',
                'label'       => 'Sisa Antrean',
                'method'      => 'GET',
                'path'        => '/antrean/sisapeserta/{nomorkartu}/{kode_poli}/{tanggalperiksa}',
                'description' => 'Meliat sisa antrean di hari H pelayanan - Header: x-token, x-username',
                'params'      => [
                    ['name' => 'nomorkartu', 'type' => 'text', 'placeholder' => 'Nomor Kartu', 'default' => ''],
                    ['name' => 'kode_poli', 'type' => 'text', 'placeholder' => 'Kode Poli', 'default' => ''],
                    ['name' => 'tanggalperiksa', 'type' => 'text', 'placeholder' => 'Tanggal (YYYY-MM-DD)', 'default' => date('Y-m-d')],
                ],
                'headers'     => ['x-token', 'x-username'],
            ],
            // Pasien Baru
            [
                'key'         => 'pasien_baru_fktp',
                'label'       => 'Pasien Baru',
                'method'      => 'POST',
                'path'        => '/peserta',
                'description' => 'Kirim informasi identitas peserta sebagai pasien baru - Header: x-token, x-username',
                'body'        => [
                    ['name' => 'nomorkartu', 'type' => 'text', 'placeholder' => 'No Kartu', 'default' => ''],
                    ['name' => 'nik', 'type' => 'text', 'placeholder' => 'NIK', 'default' => ''],
                    ['name' => 'nomorkk', 'type' => 'text', 'placeholder' => 'No KK', 'default' => ''],
                    ['name' => 'nama', 'type' => 'text', 'placeholder' => 'Nama', 'default' => ''],
                    ['name' => 'jeniskelamin', 'type' => 'text', 'placeholder' => 'Jenis Kelamin (L/P)', 'default' => ''],
                    ['name' => 'tanggallahir', 'type' => 'text', 'placeholder' => 'Tanggal Lahir (YYYY-MM-DD)', 'default' => ''],
                    ['name' => 'alamat', 'type' => 'text', 'placeholder' => 'Alamat', 'default' => ''],
                    ['name' => 'kodeprop', 'type' => 'text', 'placeholder' => 'Kode Propinsi', 'default' => ''],
                    ['name' => 'namaprop', 'type' => 'text', 'placeholder' => 'Nama Propinsi', 'default' => ''],
                    ['name' => 'kodedati2', 'type' => 'text', 'placeholder' => 'Kode Dati 2', 'default' => ''],
                    ['name' => 'namadati2', 'type' => 'text', 'placeholder' => 'Nama Dati 2', 'default' => ''],
                    ['name' => 'kodekec', 'type' => 'text', 'placeholder' => 'Kode Kecamatan', 'default' => ''],
                    ['name' => 'namakec', 'type' => 'text', 'placeholder' => 'Nama Kecamatan', 'default' => ''],
                    ['name' => 'kodekel', 'type' => 'text', 'placeholder' => 'Kode Kelurahan', 'default' => ''],
                    ['name' => 'namakel', 'type' => 'text', 'placeholder' => 'Nama Kelurahan', 'default' => ''],
                    ['name' => 'rw', 'type' => 'text', 'placeholder' => 'RW', 'default' => ''],
                    ['name' => 'rt', 'type' => 'text', 'placeholder' => 'RT', 'default' => ''],
                ],
                'headers'     => ['x-token', 'x-username'],
            ],
            // Batal Antrean
            [
                'key'         => 'batal_antrean_fktp',
                'label'       => 'Batal Antrean',
                'method'      => 'PUT',
                'path'        => '/antrean/batal',
                'description' => 'Membatalkan antrean pasien - Header: x-token, x-username',
                'body'        => [
                    ['name' => 'nomorkartu', 'type' => 'text', 'placeholder' => 'No Kartu', 'default' => ''],
                    ['name' => 'kodepoli', 'type' => 'text', 'placeholder' => 'Kode Poli', 'default' => ''],
                    ['name' => 'tanggalperiksa', 'type' => 'text', 'placeholder' => 'Tanggal Periksa (YYYY-MM-DD)', 'default' => date('Y-m-d')],
                    ['name' => 'keterangan', 'type' => 'text', 'placeholder' => 'Keterangan', 'default' => ''],
                ],
                'headers'     => ['x-token', 'x-username'],
            ],
            // Referensi Poli New
            [
                'key'         => 'ref_poli_fktp',
                'label'       => 'Referensi Poli',
                'method'      => 'GET',
                'path'        => '/ref/poli/tanggal/{tanggal}',
                'description' => 'Meliat referensi poli - Header: x-cons-id, x-timestamp, x-signature, user_key',
                'params'      => [
                    ['name' => 'tanggal', 'type' => 'text', 'placeholder' => 'Tanggal (YYYY-MM-DD)', 'default' => date('Y-m-d')],
                ],
                'headers'     => ['x-cons-id', 'x-timestamp', 'x-signature', 'user_key'],
            ],
            // Referensi Dokter New
            [
                'key'         => 'ref_dokter_fktp',
                'label'       => 'Referensi Dokter',
                'method'      => 'GET',
                'path'        => '/ref/dokter/kodepoli/{kodepoli}/tanggal/{tanggal}',
                'description' => 'Meliat list dokter per poli - Header: x-cons-id, x-timestamp, x-signature, user_key',
                'params'      => [
                    ['name' => 'kodepoli', 'type' => 'text', 'placeholder' => 'Kode Poli', 'default' => ''],
                    ['name' => 'tanggal', 'type' => 'text', 'placeholder' => 'Tanggal (YYYY-MM-DD)', 'default' => date('Y-m-d')],
                ],
                'headers'     => ['x-cons-id', 'x-timestamp', 'x-signature', 'user_key'],
            ],
            // Tambah Antrean New
            [
                'key'         => 'tambah_antrean_fktp',
                'label'       => 'Tambah Antrean',
                'method'      => 'POST',
                'path'        => '/antrean/add',
                'description' => 'Menambah antrean - Header: x-token, x-username',
                'body'        => [
                    ['name' => 'nomorkartu', 'type' => 'text', 'placeholder' => 'No Kartu BPJS', 'default' => ''],
                    ['name' => 'nik', 'type' => 'text', 'placeholder' => 'NIK Pasien', 'default' => ''],
                    ['name' => 'nohp', 'type' => 'text', 'placeholder' => 'No HP Pasien', 'default' => ''],
                    ['name' => 'kodepoli', 'type' => 'text', 'placeholder' => 'Kode Poli', 'default' => ''],
                    ['name' => 'namapoli', 'type' => 'text', 'placeholder' => 'Nama Poli', 'default' => ''],
                    ['name' => 'norm', 'type' => 'text', 'placeholder' => 'No Rekam Medis', 'default' => ''],
                    ['name' => 'tanggalperiksa', 'type' => 'text', 'placeholder' => 'Tanggal Periksa (YYYY-MM-DD)', 'default' => date('Y-m-d')],
                    ['name' => 'kodedokter', 'type' => 'number', 'placeholder' => 'Kode Dokter', 'default' => ''],
                    ['name' => 'namadokter', 'type' => 'text', 'placeholder' => 'Nama Dokter', 'default' => ''],
                    ['name' => 'jampraktek', 'type' => 'text', 'placeholder' => 'Jam Praktek', 'default' => ''],
                    ['name' => 'nomorantrean', 'type' => 'text', 'placeholder' => 'Nomor Antrean', 'default' => ''],
                    ['name' => 'angkaantrean', 'type' => 'number', 'placeholder' => 'Angka Antrean', 'default' => ''],
                    ['name' => 'keterangan', 'type' => 'text', 'placeholder' => 'Keterangan', 'default' => ''],
                ],
                'headers'     => ['x-token', 'x-username'],
            ],
            // Update Status / Panggil Antrean
            [
                'key'         => 'panggil_antrean_fktp',
                'label'       => 'Panggil Antrean',
                'method'      => 'POST',
                'path'        => '/antrean/panggil',
                'description' => 'Update status antrean hadir/tidak hadir - Header: x-cons-id, x-timestamp, x-signature, user_key',
                'body'        => [
                    ['name' => 'tanggalperiksa', 'type' => 'text', 'placeholder' => 'Tanggal Periksa (YYYY-MM-DD)', 'default' => date('Y-m-d')],
                    ['name' => 'kodepoli', 'type' => 'text', 'placeholder' => 'Kode Poli', 'default' => ''],
                    ['name' => 'nomorkartu', 'type' => 'text', 'placeholder' => 'No Kartu', 'default' => ''],
                    ['name' => 'status', 'type' => 'number', 'placeholder' => 'Status (1=Hadir, 2=Tidak Hadir)', 'default' => '1'],
                    ['name' => 'waktu', 'type' => 'number', 'placeholder' => 'Waktu (timestamp ms)', 'default' => ''],
                ],
                'headers'     => ['x-cons-id', 'x-timestamp', 'x-signature', 'user_key'],
            ],
            // Batal Antrean New
            [
                'key'         => 'batal_antrean_new_fktp',
                'label'       => 'Batal Antrean New',
                'method'      => 'POST',
                'path'        => '/antrean/batal',
                'description' => 'Membatalkan antrean pasien - Header: x-token, x-username',
                'body'        => [
                    ['name' => 'nomorkartu', 'type' => 'text', 'placeholder' => 'No Kartu', 'default' => ''],
                    ['name' => 'kodepoli', 'type' => 'text', 'placeholder' => 'Kode Poli', 'default' => ''],
                    ['name' => 'tanggalperiksa', 'type' => 'text', 'placeholder' => 'Tanggal Periksa (YYYY-MM-DD)', 'default' => date('Y-m-d')],
                ],
                'headers'     => ['x-token', 'x-username'],
            ],
        ],
    ];