<?php
return [
        'label'       => 'Apotek',
        'icon'        => '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v7a2 2 0 01-2 2H5a2 2 0 01-2-2v-7a2 2 0 012-2m14 0V9a2 2 0 00-2-2M7 13h5m-5-4h2m8 0h2"/></svg>',
        'description' => 'Modul Apotek – Data Obat & Farmasi',
        'base_url'    => getBaseUrl('apotek', $currentDomain, $isDevMode),
        'sub_modules' => [
            [
                'key'         => 'dpho',
                'label'       => 'DPHO',
                'method'      => 'GET',
                'path'        => '/referensi/dpho',
                'description' => 'Daftar Obat DPHO',
                'params'      => [],
            ],
            [
                'key'         => 'poli_obat',
                'label'       => 'Poli',
                'method'      => 'GET',
                'path'        => '/referensi/poli/{parameter}',
                'description' => 'Daftar Obat Poli - Parameter: Kode atau Nama Poli',
                'params'      => [
                    ['name' => 'parameter', 'type' => 'text', 'placeholder' => 'Kode atau Nama Poli', 'default' => ''],
                ],
            ],
            [
                'key'         => 'faskes',
                'label'       => 'Fasilitas Kesehatan',
                'method'      => 'GET',
                'path'        => '/referensi/ppk/{parameter1}/{parameter2}',
                'description' => 'Pencarian data fasilitas kesehatan - Parameter1: Jenis Faskes (1. Faskes 1, 2. Faskes 2/RS), Parameter2: nama faskes',
                'params'      => [
                    ['name' => 'parameter1', 'type' => 'text', 'placeholder' => 'Jenis Faskes (1 atau 2)', 'default' => ''],
                    ['name' => 'parameter2', 'type' => 'text', 'placeholder' => 'Nama Faskes', 'default' => ''],
                ],
            ],
            [
                'key'         => 'setting_ppk',
                'label'       => 'Setting Apotek',
                'method'      => 'GET',
                'path'        => '/referensi/settingppk/read/{parameter}',
                'description' => 'Pencarian Setting Apotek - Parameter: Kode Apotek',
                'params'      => [
                    ['name' => 'parameter', 'type' => 'text', 'placeholder' => 'Kode Apotek', 'default' => ''],
                ],
            ],
            [
                'key'         => 'spesialistik',
                'label'       => 'Spesialistik',
                'method'      => 'GET',
                'path'        => '/referensi/spesialistik',
                'description' => 'Pencarian data spesialistik',
                'params'      => [],
            ],
            [
                'key'         => 'obat',
                'label'       => 'Obat',
                'method'      => 'GET',
                'path'        => '/referensi/obat/{parameter1}/{parameter2}/{parameter3}',
                'description' => 'Pencarian obat - Parameter1: Kode Jenis Obat, Parameter2: Tgl Resep, Parameter3: Filter Pencarian',
                'params'      => [
                    ['name' => 'parameter1', 'type' => 'text', 'placeholder' => 'Kode Jenis Obat', 'default' => ''],
                    ['name' => 'parameter2', 'type' => 'text', 'placeholder' => 'Tgl Resep (YYYY-MM-DD)', 'default' => ''],
                    ['name' => 'parameter3', 'type' => 'text', 'placeholder' => 'Filter Pencarian', 'default' => ''],
                ],
            ],
            [
                'key'         => 'obat_non_racikan',
                'label'       => 'Penyimpanan Obat Non Racikan',
                'method'      => 'POST',
                'path'        => '/obatnonracikan/v3/insert',
                'description' => 'Simpan Obat Non Racikan',
                'body'        => [
                    ['name' => 'NOSJP', 'type' => 'text', 'placeholder' => 'No SJP', 'default' => ''],
                    ['name' => 'NORESEP', 'type' => 'text', 'placeholder' => 'No Resep', 'default' => ''],
                    ['name' => 'KDOBT', 'type' => 'text', 'placeholder' => 'Kode Obat', 'default' => ''],
                    ['name' => 'NMOBAT', 'type' => 'text', 'placeholder' => 'Nama Obat', 'default' => ''],
                    ['name' => 'SIGNA1OBT', 'type' => 'number', 'placeholder' => 'Signa 1', 'default' => ''],
                    ['name' => 'SIGNA2OBT', 'type' => 'number', 'placeholder' => 'Signa 2', 'default' => ''],
                    ['name' => 'JMLOBT', 'type' => 'number', 'placeholder' => 'Jumlah Obat', 'default' => ''],
                    ['name' => 'JHO', 'type' => 'number', 'placeholder' => 'Jumlah Hari Obat', 'default' => ''],
                    ['name' => 'CatKhsObt', 'type' => 'text', 'placeholder' => 'Catatan Khusus Obat', 'default' => ''],
                ],
            ],
            [
                'key'         => 'obat_racikan',
                'label'       => 'Penyimpanan Obat Racikan',
                'method'      => 'POST',
                'path'        => '/obatracikan/v3/insert',
                'description' => 'Simpan Obat Racikan',
                'body'        => [
                    ['name' => 'NOSJP', 'type' => 'text', 'placeholder' => 'No SJP', 'default' => ''],
                    ['name' => 'NORESEP', 'type' => 'text', 'placeholder' => 'No Resep', 'default' => ''],
                    ['name' => 'JNSROBT', 'type' => 'text', 'placeholder' => 'Jenis Racikan (R.01)', 'default' => ''],
                    ['name' => 'KDOBT', 'type' => 'text', 'placeholder' => 'Kode Obat', 'default' => ''],
                    ['name' => 'NMOBAT', 'type' => 'text', 'placeholder' => 'Nama Obat', 'default' => ''],
                    ['name' => 'SIGNA1OBT', 'type' => 'number', 'placeholder' => 'Signa 1', 'default' => ''],
                    ['name' => 'SIGNA2OBT', 'type' => 'number', 'placeholder' => 'Signa 2', 'default' => ''],
                    ['name' => 'PERMINTAAN', 'type' => 'number', 'placeholder' => 'Permintaan', 'default' => ''],
                    ['name' => 'JMLOBT', 'type' => 'number', 'placeholder' => 'Jumlah Obat', 'default' => ''],
                    ['name' => 'JHO', 'type' => 'number', 'placeholder' => 'Jumlah Hari Obat', 'default' => ''],
                    ['name' => 'CatKhsObt', 'type' => 'text', 'placeholder' => 'Catatan Khusus Obat', 'default' => ''],
                ],
            ],
            [
                'key'         => 'update_stok_obat',
                'label'       => 'Update Stok Obat',
                'method'      => 'POST',
                'path'        => '/UpdateStokObat/updatestok',
                'description' => 'Menerima data stok obat dari sistem informasi apotek',
                'body'        => [
                    ['name' => 'KDOBAT', 'type' => 'text', 'placeholder' => 'Kode Obat', 'default' => ''],
                    ['name' => 'STOK', 'type' => 'number', 'placeholder' => 'Stok', 'default' => ''],
                ],
            ],
            [
                'key'         => 'hapus_pelayanan_obat',
                'label'       => 'Hapus Pelayanan Obat',
                'method'      => 'DELETE',
                'path'        => '/pelayanan/obat/hapus/',
                'description' => 'Hapus Pelayanan Obat',
                'body'        => [
                    ['name' => 'nosepapotek', 'type' => 'text', 'placeholder' => 'No SEP Apotek', 'default' => ''],
                    ['name' => 'noresep', 'type' => 'text', 'placeholder' => 'No Resep', 'default' => ''],
                    ['name' => 'kodeobat', 'type' => 'text', 'placeholder' => 'Kode Obat', 'default' => ''],
                    ['name' => 'tipeobat', 'type' => 'text', 'placeholder' => 'Tipe Obat (N/P)', 'default' => 'N'],
                ],
            ],
            [
                'key'         => 'daftar_pelayanan_obat',
                'label'       => 'Daftar Pelayanan Obat',
                'method'      => 'GET',
                'path'        => '/obat/daftar/{parameter}',
                'description' => 'Daftar Pelayanan Obat - Parameter: Nomor Kunjungan/SEP',
                'params'      => [
                    ['name' => 'parameter', 'type' => 'text', 'placeholder' => 'Nomor Kunjungan/SEP', 'default' => ''],
                ],
            ],
            [
                'key'         => 'riwayat_pelayanan_obat',
                'label'       => 'Riwayat Pelayanan Obat',
                'method'      => 'GET',
                'path'        => '/riwayatobat/{parameter1}/{parameter2}/{parameter3}',
                'description' => 'Riwayat Pelayanan Obat - Parameter1: Tgl Awal, Parameter2: Tgl Akhir, Parameter3: NoKartu',
                'params'      => [
                    ['name' => 'parameter1', 'type' => 'text', 'placeholder' => 'Tgl Awal (YYYY-MM-DD)', 'default' => ''],
                    ['name' => 'parameter2', 'type' => 'text', 'placeholder' => 'Tgl Akhir (YYYY-MM-DD)', 'default' => ''],
                    ['name' => 'parameter3', 'type' => 'text', 'placeholder' => 'No Kartu', 'default' => ''],
                ],
            ],
            [
                'key'         => 'simpan_resep',
                'label'       => 'Simpan Resep',
                'method'      => 'POST',
                'path'        => '/sjpresep/v3/insert',
                'description' => 'Simpan Resep',
                'body'        => [
                    ['name' => 'TGLSJP', 'type' => 'text', 'placeholder' => 'Tgl SJP (YYYY-MM-DD HH:MM:SS)', 'default' => ''],
                    ['name' => 'REFASALSJP', 'type' => 'text', 'placeholder' => 'Ref Asal SJP', 'default' => ''],
                    ['name' => 'POLIRSP', 'type' => 'text', 'placeholder' => 'Poli RS', 'default' => ''],
                    ['name' => 'KDJNSOBAT', 'type' => 'text', 'placeholder' => 'Jns Obat (1. PRB, 2. Kronis, 3. Kemoterapi)', 'default' => ''],
                    ['name' => 'NORESEP', 'type' => 'text', 'placeholder' => 'No Resep', 'default' => ''],
                    ['name' => 'IDUSERSJP', 'type' => 'text', 'placeholder' => 'ID User SJP', 'default' => ''],
                    ['name' => 'TGLRSP', 'type' => 'text', 'placeholder' => 'Tgl RSP (YYYY-MM-DD HH:MM:SS)', 'default' => ''],
                    ['name' => 'TGLPELRSP', 'type' => 'text', 'placeholder' => 'Tgl Pelayanan RSP (YYYY-MM-DD HH:MM:SS)', 'default' => ''],
                    ['name' => 'KdDokter', 'type' => 'text', 'placeholder' => 'Kode Dokter', 'default' => ''],
                    ['name' => 'iterasi', 'type' => 'text', 'placeholder' => 'Iterasi (0. Non Iterasi, 1. Iterasi)', 'default' => '0'],
                ],
            ],
            [
                'key'         => 'hapus_resep',
                'label'       => 'Hapus Resep',
                'method'      => 'DELETE',
                'path'        => '/hapusresep',
                'description' => 'Hapus Resep',
                'body'        => [
                    ['name' => 'nosjp', 'type' => 'text', 'placeholder' => 'No SJP', 'default' => ''],
                    ['name' => 'refasalsjp', 'type' => 'text', 'placeholder' => 'Ref Asal SJP', 'default' => ''],
                    ['name' => 'noresep', 'type' => 'text', 'placeholder' => 'No Resep', 'default' => ''],
                ],
            ],
            [
                'key'         => 'daftar_resep',
                'label'       => 'Daftar Resep',
                'method'      => 'POST',
                'path'        => '/daftarresep',
                'description' => 'Daftar Resep',
                'body'        => [
                    ['name' => 'kdppk', 'type' => 'text', 'placeholder' => 'Kode PPK', 'default' => ''],
                    ['name' => 'KdJnsObat', 'type' => 'text', 'placeholder' => 'Kode Jenis Obat', 'default' => ''],
                    ['name' => 'JnsTgl', 'type' => 'text', 'placeholder' => 'Jns Tgl (TGLPELSJP/TGLRSP)', 'default' => ''],
                    ['name' => 'TglMulai', 'type' => 'text', 'placeholder' => 'Tgl Mulai (YYYY-MM-DD HH:MM:SS)', 'default' => ''],
                    ['name' => 'TglAkhir', 'type' => 'text', 'placeholder' => 'Tgl Akhir (YYYY-MM-DD HH:MM:SS)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep',
                'label'       => 'Cari No Kunjungan/SEP',
                'method'      => 'GET',
                'path'        => '/sep/{parameter}',
                'description' => 'Data No Kunjungan/SEP - Parameter: Nomor Kunjungan/SEP (19 digit)',
                'params'      => [
                    ['name' => 'parameter', 'type' => 'text', 'placeholder' => 'Nomor Kunjungan/SEP (19 digit)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'monitoring_klaim',
                'label'       => 'Data Klaim',
                'method'      => 'GET',
                'path'        => '/monitoring/klaim/{parameter1}/{parameter2}/{parameter3}/{parameter4}',
                'description' => 'Data Klaim - Parameter1: Bulan, Parameter2: Tahun, Parameter3: Jenis Obat (0. Semua, 1. PRB, 2. Kronis, 3. Kemoterapi), Parameter4: Status (1. Belum diverifikasi, 2. Sudah Verifikasi)',
                'params'      => [
                    ['name' => 'parameter1', 'type' => 'text', 'placeholder' => 'Bulan (01-12)', 'default' => ''],
                    ['name' => 'parameter2', 'type' => 'text', 'placeholder' => 'Tahun (YYYY)', 'default' => ''],
                    ['name' => 'parameter3', 'type' => 'text', 'placeholder' => 'Jenis Obat (0/1/2/3)', 'default' => ''],
                    ['name' => 'parameter4', 'type' => 'text', 'placeholder' => 'Status (1/2)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'rekap_peserta_prb',
                'label'       => 'Rekap Peserta PRB',
                'method'      => 'GET',
                'path'        => '/Prb/rekappeserta/tahun/{parameter1}/bulan/{parameter2}',
                'description' => 'Rekap peserta PRB - Parameter1: Tahun, Parameter2: Bulan',
                'params'      => [
                    ['name' => 'parameter1', 'type' => 'text', 'placeholder' => 'Tahun (YYYY)', 'default' => ''],
                    ['name' => 'parameter2', 'type' => 'text', 'placeholder' => 'Bulan (01-12)', 'default' => ''],
                ],
            ],
        ],
    ];