<?php
return [
        'label'       => 'VClaim',
        'icon'        => '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h4m7-6v-2a4 4 0 00-4-4H9a4 4 0 00-4 4v10a4 4 0 004 4h6a4 4 0 004-4V12z"/></svg>',
        'description' => 'Modul VClaim – Klaim & Jaminan Peserta',
        'base_url'    => getBaseUrl('vclaim', $currentDomain, $isDevMode),
        'sub_modules' => [
            // Lembar Pengajuan Klaim (LPK)
            [
                'key'         => 'lpk_insert',
                'label'       => 'Insert LPK',
                'method'      => 'POST',
                'path'        => '/LPK/insert',
                'description' => 'Insert Rujukan Lembar Pengajuan Klaim',
                'body'        => [
                    ['name' => 'request', 'type' => 'json', 'placeholder' => 'JSON body LPK', 'default' => ''],
                ],
            ],
            [
                'key'         => 'lpk_update',
                'label'       => 'Update LPK',
                'method'      => 'PUT',
                'path'        => '/LPK/update',
                'description' => 'Update Rujukan Lembar Pengajuan Klaim',
                'body'        => [
                    ['name' => 'request', 'type' => 'json', 'placeholder' => 'JSON body LPK', 'default' => ''],
                ],
            ],
            [
                'key'         => 'lpk_delete',
                'label'       => 'Delete LPK',
                'method'      => 'DELETE',
                'path'        => '/LPK/delete',
                'description' => 'Delete Rujukan Lembar Pengajuan Klaim',
                'body'        => [
                    ['name' => 'request', 'type' => 'json', 'placeholder' => 'JSON body LPK', 'default' => ''],
                ],
            ],
            [
                'key'         => 'lpk_data',
                'label'       => 'Data Lembar Pengajuan Klaim',
                'method'      => 'GET',
                'path'        => '/LPK/TglMasuk/{tglMasuk}/JnsPelayanan/{jnsPelayanan}',
                'description' => 'Pencarian data peserta berdasarkan tanggal masuk dan jenis pelayanan',
                'params'      => [
                    ['name' => 'tglMasuk', 'type' => 'text', 'placeholder' => 'Tanggal Masuk (yyyy-MM-dd)', 'default' => ''],
                    ['name' => 'jnsPelayanan', 'type' => 'text', 'placeholder' => 'Jenis Pelayanan (1=Inap, 2=Jalan)', 'default' => ''],
                ],
            ],
            // Monitoring
            [
                'key'         => 'monitoring_kunjungan',
                'label'       => 'Data Kunjungan',
                'method'      => 'GET',
                'path'        => '/Monitoring/Kunjungan/Tanggal/{tanggal}/JnsPelayanan/{jnsPelayanan}',
                'description' => 'Data Kunjungan berdasarkan tanggal dan jenis pelayanan',
                'params'      => [
                    ['name' => 'tanggal', 'type' => 'text', 'placeholder' => 'Tanggal (yyyy-MM-dd)', 'default' => ''],
                    ['name' => 'jnsPelayanan', 'type' => 'text', 'placeholder' => 'Jenis Pelayanan (1=Inap, 2=Jalan)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'monitoring_klaim',
                'label'       => 'Data Klaim',
                'method'      => 'GET',
                'path'        => '/Monitoring/Klaim/Tanggal/{tglPulang}/JnsPelayanan/{jnsPelayanan}/Status/{status}',
                'description' => 'Data Klaim berdasarkan tanggal pulang, jenis pelayanan, dan status',
                'params'      => [
                    ['name' => 'tglPulang', 'type' => 'text', 'placeholder' => 'Tanggal Pulang (yyyy-MM-dd)', 'default' => ''],
                    ['name' => 'jnsPelayanan', 'type' => 'text', 'placeholder' => 'Jenis Pelayanan (1=Inap, 2=Jalan)', 'default' => ''],
                    ['name' => 'status', 'type' => 'text', 'placeholder' => 'Status Klaim (1=Proses, 2=Pending, 3=Klaim)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'monitoring_histori',
                'label'       => 'Histori Pelayanan Peserta',
                'method'      => 'GET',
                'path'        => '/monitoring/HistoriPelayanan/NoKartu/{noKartu}/tglMulai/{tglMulai}/tglAkhir/{tglAkhir}',
                'description' => 'Histori Pelayanan Per Peserta',
                'params'      => [
                    ['name' => 'noKartu', 'type' => 'text', 'placeholder' => 'Nomor Kartu Peserta', 'default' => ''],
                    ['name' => 'tglMulai', 'type' => 'text', 'placeholder' => 'Tanggal Mulai (yyyy-MM-dd)', 'default' => ''],
                    ['name' => 'tglAkhir', 'type' => 'text', 'placeholder' => 'Tanggal Akhir (yyyy-MM-dd)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'monitoring_jasa_raharja',
                'label'       => 'Klaim Jaminan Jasa Raharja',
                'method'      => 'GET',
                'path'        => '/monitoring/JasaRaharja/JnsPelayanan/{jnsPelayanan}/tglMulai/{tglMulai}/tglAkhir/{tglAkhir}',
                'description' => 'Monitoring Klaim Jaminan Jasa Raharja',
                'params'      => [
                    ['name' => 'jnsPelayanan', 'type' => 'text', 'placeholder' => 'Jenis Pelayanan (1=Inap, 2=Jalan)', 'default' => ''],
                    ['name' => 'tglMulai', 'type' => 'text', 'placeholder' => 'Tanggal Mulai (yyyy-MM-dd)', 'default' => ''],
                    ['name' => 'tglAkhir', 'type' => 'text', 'placeholder' => 'Tanggal Akhir (yyyy-MM-dd)', 'default' => ''],
                ],
            ],
            // Peserta
            [
                'key'         => 'peserta_kartu',
                'label'       => 'Peserta by No Kartu',
                'method'      => 'GET',
                'path'        => '/Peserta/nokartu/{noKartu}/tglSEP/{tglSEP}',
                'description' => 'Pencarian data peserta BPJS Kesehatan',
                'params'      => [
                    ['name' => 'noKartu', 'type' => 'text', 'placeholder' => 'Nomor Kartu Peserta', 'default' => ''],
                    ['name' => 'tglSEP', 'type' => 'text', 'placeholder' => 'Tanggal SEP (yyyy-MM-dd)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'peserta_nik',
                'label'       => 'Peserta by NIK',
                'method'      => 'GET',
                'path'        => '/Peserta/nik/{nik}/tglSEP/{tglSEP}',
                'description' => 'Pencarian data peserta berdasarkan NIK Kependudukan',
                'params'      => [
                    ['name' => 'nik', 'type' => 'text', 'placeholder' => 'NIK Peserta', 'default' => ''],
                    ['name' => 'tglSEP', 'type' => 'text', 'placeholder' => 'Tanggal SEP (yyyy-MM-dd)', 'default' => ''],
                ],
            ],
            // PRB (Rujukan Balik)
            [
                'key'         => 'prb_insert',
                'label'       => 'Insert PRB',
                'method'      => 'POST',
                'path'        => '/PRB/insert',
                'description' => 'Insert Rujuk Balik (PRB)',
                'body'        => [
                    ['name' => 'request', 'type' => 'json', 'placeholder' => 'JSON body PRB', 'default' => ''],
                ],
            ],
            [
                'key'         => 'prb_update',
                'label'       => 'Update PRB',
                'method'      => 'PUT',
                'path'        => '/PRB/Update',
                'description' => 'Update PRB',
                'body'        => [
                    ['name' => 'request', 'type' => 'json', 'placeholder' => 'JSON body PRB', 'default' => ''],
                ],
            ],
            [
                'key'         => 'prb_delete',
                'label'       => 'Delete PRB',
                'method'      => 'DELETE',
                'path'        => '/PRB/Delete',
                'description' => 'Hapus Data PRB',
                'body'        => [
                    ['name' => 'request', 'type' => 'json', 'placeholder' => 'JSON body PRB', 'default' => ''],
                ],
            ],
            [
                'key'         => 'prb_cari_srb',
                'label'       => 'Cari PRB by SRB',
                'method'      => 'GET',
                'path'        => '/prb/{noSrb}/nosep/{noSep}',
                'description' => 'Pencarian data PRB berdasarkan Nomor SRB dan No SEP',
                'params'      => [
                    ['name' => 'noSrb', 'type' => 'text', 'placeholder' => 'Nomor SRB', 'default' => ''],
                    ['name' => 'noSep', 'type' => 'text', 'placeholder' => 'Nomor SEP', 'default' => ''],
                ],
            ],
            [
                'key'         => 'prb_cari_tanggal',
                'label'       => 'Cari PRB by Tanggal',
                'method'      => 'GET',
                'path'        => '/prb/tglMulai/{tglMulai}/tglAkhir/{tglAkhir}',
                'description' => 'Pencarian data PRB berdasarkan Tanggal SRB',
                'params'      => [
                    ['name' => 'tglMulai', 'type' => 'text', 'placeholder' => 'Tanggal Mulai (yyyy-MM-dd)', 'default' => ''],
                    ['name' => 'tglAkhir', 'type' => 'text', 'placeholder' => 'Tanggal Akhir (yyyy-MM-dd)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'prb_potensi',
                'label'       => 'Rekap Potensi PRB',
                'method'      => 'GET',
                'path'        => '/prbpotensi/tahun/{tahun}/bulan/{bulan}',
                'description' => 'Rekap data peserta potensi PRB',
                'params'      => [
                    ['name' => 'tahun', 'type' => 'text', 'placeholder' => 'Tahun (yyyy)', 'default' => ''],
                    ['name' => 'bulan', 'type' => 'text', 'placeholder' => 'Bulan (01-12)', 'default' => ''],
                ],
            ],
            // Referensi
            [
                'key'         => 'ref_diagnosa',
                'label'       => 'Referensi Diagnosa',
                'method'      => 'GET',
                'path'        => '/referensi/diagnosa/{param}',
                'description' => 'Pencarian data diagnosa (ICD-10)',
                'params'      => [
                    ['name' => 'param', 'type' => 'text', 'placeholder' => 'Kode atau Nama Diagnosa', 'default' => ''],
                ],
            ],
            [
                'key'         => 'ref_poli',
                'label'       => 'Referensi Poli',
                'method'      => 'GET',
                'path'        => '/referensi/poli/{param}',
                'description' => 'Pencarian data poli',
                'params'      => [
                    ['name' => 'param', 'type' => 'text', 'placeholder' => 'Kode atau Nama Poli', 'default' => ''],
                ],
            ],
            [
                'key'         => 'ref_faskes',
                'label'       => 'Referensi Faskes',
                'method'      => 'GET',
                'path'        => '/referensi/faskes/{param1}/{param2}',
                'description' => 'Pencarian data fasilitas kesehatan',
                'params'      => [
                    ['name' => 'param1', 'type' => 'text', 'placeholder' => 'Nama atau Kode Faskes', 'default' => ''],
                    ['name' => 'param2', 'type' => 'text', 'placeholder' => 'Jenis Faskes (1=Faskes 1, 2=Faskes 2)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'ref_dokter_pelayanan',
                'label'       => 'Referensi Dokter DPJP',
                'method'      => 'GET',
                'path'        => '/referensi/dokter/pelayanan/{jnsPelayanan}/tglPelayanan/{tglPelayanan}/Spesialis/{spesialis}',
                'description' => 'Pencarian data dokter DPJP untuk pengisian DPJP Layan',
                'params'      => [
                    ['name' => 'jnsPelayanan', 'type' => 'text', 'placeholder' => 'Jenis Pelayanan (1=Inap, 2=Jalan)', 'default' => ''],
                    ['name' => 'tglPelayanan', 'type' => 'text', 'placeholder' => 'Tanggal Pelayanan (yyyy-MM-dd)', 'default' => ''],
                    ['name' => 'spesialis', 'type' => 'text', 'placeholder' => 'Kode Spesialis/Subspesialis', 'default' => ''],
                ],
            ],
            [
                'key'         => 'ref_propinsi',
                'label'       => 'Referensi Propinsi',
                'method'      => 'GET',
                'path'        => '/referensi/propinsi',
                'description' => 'Pencarian data propinsi',
                'params'      => [],
            ],
            [
                'key'         => 'ref_kabupaten',
                'label'       => 'Referensi Kabupaten',
                'method'      => 'GET',
                'path'        => '/referensi/kabupaten/propinsi/{kodePropinsi}',
                'description' => 'Pencarian data kabupaten berdasarkan kode propinsi',
                'params'      => [
                    ['name' => 'kodePropinsi', 'type' => 'text', 'placeholder' => 'Kode Propinsi', 'default' => ''],
                ],
            ],
            [
                'key'         => 'ref_kecamatan',
                'label'       => 'Referensi Kecamatan',
                'method'      => 'GET',
                'path'        => '/referensi/kecamatan/kabupaten/{kodeKabupaten}',
                'description' => 'Pencarian data kecamatan berdasarkan kode kabupaten',
                'params'      => [
                    ['name' => 'kodeKabupaten', 'type' => 'text', 'placeholder' => 'Kode Kabupaten', 'default' => ''],
                ],
            ],
            [
                'key'         => 'ref_diagnosaprb',
                'label'       => 'Referensi Diagnosa PRB',
                'method'      => 'GET',
                'path'        => '/referensi/diagnosaprb',
                'description' => 'Pencarian data diagnosa program PRB',
                'params'      => [],
            ],
            [
                'key'         => 'ref_obatprb',
                'label'       => 'Referensi Obat PRB',
                'method'      => 'GET',
                'path'        => '/referensi/obatprb/{param}',
                'description' => 'Pencarian data obat generik PRB',
                'params'      => [
                    ['name' => 'param', 'type' => 'text', 'placeholder' => 'Nama Obat Generik', 'default' => ''],
                ],
            ],
            [
                'key'         => 'ref_procedure',
                'label'       => 'Referensi Procedure',
                'method'      => 'GET',
                'path'        => '/referensi/procedure/{param}',
                'description' => 'Pencarian data procedure/tindakan',
                'params'      => [
                    ['name' => 'param', 'type' => 'text', 'placeholder' => 'Nama atau Kode Procedure', 'default' => ''],
                ],
            ],
            [
                'key'         => 'ref_kelasrawat',
                'label'       => 'Referensi Kelas Rawat',
                'method'      => 'GET',
                'path'        => '/referensi/kelasrawat',
                'description' => 'Pencarian data kelas rawat',
                'params'      => [],
            ],
            [
                'key'         => 'ref_dokter',
                'label'       => 'Referensi Dokter',
                'method'      => 'GET',
                'path'        => '/referensi/dokter/{param}',
                'description' => 'Pencarian data dokter dalam faskes sesuai consid',
                'params'      => [
                    ['name' => 'param', 'type' => 'text', 'placeholder' => 'Nama Dokter/DPJP', 'default' => ''],
                ],
            ],
            [
                'key'         => 'ref_spesialistik',
                'label'       => 'Referensi Spesialistik',
                'method'      => 'GET',
                'path'        => '/referensi/spesialistik',
                'description' => 'Pencarian data spesialistik',
                'params'      => [],
            ],
            [
                'key'         => 'ref_ruangrawat',
                'label'       => 'Referensi Ruang Rawat',
                'method'      => 'GET',
                'path'        => '/referensi/ruangrawat',
                'description' => 'Pencarian data ruang rawat',
                'params'      => [],
            ],
            // ===== SEP ENDPOINTS =====
            [
                'key'         => 'sep_insert',
                'label'       => 'Insert SEP',
                'method'      => 'POST',
                'path'        => '/SEP/insert',
                'description' => 'Insert SEP (Surat Bukti Jaminan Pelayanan)',
                'body'        => [
                    ['name' => 'request', 'type' => 'json', 'placeholder' => 'JSON body SEP', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_update',
                'label'       => 'Update SEP',
                'method'      => 'POST',
                'path'        => '/SEP/update',
                'description' => 'Update SEP',
                'body'        => [
                    ['name' => 'request', 'type' => 'json', 'placeholder' => 'JSON body SEP', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_delete',
                'label'       => 'Delete SEP',
                'method'      => 'DELETE',
                'path'        => '/SEP/delete',
                'description' => 'Hapus Data SEP',
                'body'        => [
                    ['name' => 'request', 'type' => 'json', 'placeholder' => 'JSON body SEP', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_cari',
                'label'       => 'Cari SEP',
                'method'      => 'GET',
                'path'        => '/SEP/{parameter}',
                'description' => 'Melihat data detail SEP Peserta',
                'params'      => [
                    ['name' => 'parameter', 'type' => 'text', 'placeholder' => 'Nomor SEP Peserta (19 digit)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_insert_20',
                'label'       => 'Insert SEP 2.0',
                'method'      => 'POST',
                'path'        => '/SEP/2.0/insert',
                'description' => 'Insert SEP versi 2.0',
                'body'        => [
                    ['name' => 'request', 'type' => 'json', 'placeholder' => 'JSON body SEP 2.0', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_update_20',
                'label'       => 'Update SEP 2.0',
                'method'      => 'POST',
                'path'        => '/SEP/2.0/update',
                'description' => 'Update SEP versi 2.0',
                'body'        => [
                    ['name' => 'request', 'type' => 'json', 'placeholder' => 'JSON body SEP 2.0', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_delete_20',
                'label'       => 'Delete SEP 2.0',
                'method'      => 'POST',
                'path'        => '/SEP/2.0/delete',
                'description' => 'Hapus SEP versi 2.0',
                'body'        => [
                    ['name' => 'request', 'type' => 'json', 'placeholder' => 'JSON body SEP 2.0', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_internal',
                'label'       => 'Data SEP Internal',
                'method'      => 'GET',
                'path'        => '/SEP/Internal/{parameter}',
                'description' => 'Data SEP Internal',
                'params'      => [
                    ['name' => 'parameter', 'type' => 'text', 'placeholder' => 'Nomor SEP (19 digit)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_internal_delete',
                'label'       => 'Hapus SEP Internal',
                'method'      => 'POST',
                'path'        => '/SEP/Internal/delete',
                'description' => 'Hapus SEP Internal',
                'body'        => [
                    ['name' => 'request', 'type' => 'json', 'placeholder' => 'JSON body', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_rujukan_lastsep',
                'label'       => 'Cari SEP Terakhir by No Rujukan',
                'method'      => 'GET',
                'path'        => '/Rujukan/lastsep/norujukan/{parameter}',
                'description' => 'Melihat data detail SEP Terakhir Peserta Berdasarkan Nomor Rujukan',
                'params'      => [
                    ['name' => 'parameter', 'type' => 'text', 'placeholder' => 'Nomor Rujukan', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_cari_by_kartu',
                'label'       => 'Cari SEP by No Kartu',
                'method'      => 'GET',
                'path'        => '/Peserta/nokartu/{parameter1}/tglSEP/{parameter2}',
                'description' => 'Pencarian data peserta BPJS Kesehatan',
                'params'      => [
                    ['name' => 'parameter1', 'type' => 'text', 'placeholder' => 'Nomor Kartu Peserta', 'default' => ''],
                    ['name' => 'parameter2', 'type' => 'text', 'placeholder' => 'Tanggal SEP (yyyy-MM-dd)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_cari_by_nik',
                'label'       => 'Cari SEP by NIK',
                'method'      => 'GET',
                'path'        => '/Peserta/nik/{parameter1}/tglSEP/{parameter2}',
                'description' => 'Pencarian data peserta berdasarkan NIK Kependudukan',
                'params'      => [
                    ['name' => 'parameter1', 'type' => 'text', 'placeholder' => 'NIK Peserta', 'default' => ''],
                    ['name' => 'parameter2', 'type' => 'text', 'placeholder' => 'Tanggal SEP (yyyy-MM-dd)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_rujukan_insert',
                'label'       => 'Insert Rujukan',
                'method'      => 'POST',
                'path'        => '/Rujukan/insert',
                'description' => 'Insert Rujukan',
                'body'        => [
                    ['name' => 'request', 'type' => 'json', 'placeholder' => 'JSON body rujukan', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_rujukan_update',
                'label'       => 'Update Rujukan',
                'method'      => 'PUT',
                'path'        => '/Rujukan/update',
                'description' => 'Update Rujukan',
                'body'        => [
                    ['name' => 'request', 'type' => 'json', 'placeholder' => 'JSON body rujukan', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_rujukan_delete',
                'label'       => 'Delete Rujukan',
                'method'      => 'DELETE',
                'path'        => '/Rujukan/delete',
                'description' => 'Hapus Data Rujukan',
                'body'        => [
                    ['name' => 'request', 'type' => 'json', 'placeholder' => 'JSON body rujukan', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_rujukan_cari',
                'label'       => 'Cari Rujukan by No',
                'method'      => 'GET',
                'path'        => '/Rujukan/{parameter}',
                'description' => 'Pencarian data rujukan berdasarkan nomor rujukan',
                'params'      => [
                    ['name' => 'parameter', 'type' => 'text', 'placeholder' => 'Nomor Rujukan', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_rujukan_rs',
                'label'       => 'Cari Rujukan by No (RS)',
                'method'      => 'GET',
                'path'        => '/Rujukan/RS/{parameter}',
                'description' => 'Pencarian data rujukan dari rumah sakit berdasarkan nomor rujukan',
                'params'      => [
                    ['name' => 'parameter', 'type' => 'text', 'placeholder' => 'Nomor Rujukan', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_rujukan_peserta',
                'label'       => 'Cari Rujukan by No Kartu (PCare)',
                'method'      => 'GET',
                'path'        => '/Rujukan/Peserta/{parameter}',
                'description' => 'Pencarian data rujukan dari PCare berdasarkan nomor kartu',
                'params'      => [
                    ['name' => 'parameter', 'type' => 'text', 'placeholder' => 'Nomor Kartu', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_rujukan_rs_peserta',
                'label'       => 'Cari Rujukan by No Kartu (RS)',
                'method'      => 'GET',
                'path'        => '/Rujukan/RS/Peserta/{parameter}',
                'description' => 'Pencarian data rujukan dari rumah sakit berdasarkan nomor kartu',
                'params'      => [
                    ['name' => 'parameter', 'type' => 'text', 'placeholder' => 'Nomor Kartu', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_rujukan_list_peserta',
                'label'       => 'Cari Rujukan List by No Kartu',
                'method'      => 'GET',
                'path'        => '/Rujukan/List/Peserta/{parameter}',
                'description' => 'Pencarian data rujukan dari PCare berdasarkan nomor kartu (multi record)',
                'params'      => [
                    ['name' => 'parameter', 'type' => 'text', 'placeholder' => 'Nomor Kartu', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_rujukan_rs_list_peserta',
                'label'       => 'Cari Rujukan List by No Kartu (RS)',
                'method'      => 'GET',
                'path'        => '/Rujukan/RS/List/Peserta/{parameter}',
                'description' => 'Pencarian data rujukan dari rumah sakit berdasarkan nomor kartu (multi record)',
                'params'      => [
                    ['name' => 'parameter', 'type' => 'text', 'placeholder' => 'Nomor Kartu', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_rencana_kontrol',
                'label'       => 'Rencana Kontrol',
                'method'      => 'GET',
                'path'        => '/RencanaKontrol/nosep/{parameter}',
                'description' => 'Melihat data SEP untuk keperluan rencana kontrol',
                'params'      => [
                    ['name' => 'parameter', 'type' => 'text', 'placeholder' => 'Nomor SEP Peserta', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_rencana_kontrol_surat',
                'label'       => 'Data Nomor Surat Kontrol',
                'method'      => 'GET',
                'path'        => '/RencanaKontrol/noSuratKontrol/{parameter}',
                'description' => 'Melihat data SEP untuk keperluan rencana kontrol',
                'params'      => [
                    ['name' => 'parameter', 'type' => 'text', 'placeholder' => 'Nomor Surat Kontrol', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_rencana_kontrol_list',
                'label'       => 'List Rencana Kontrol',
                'method'      => 'GET',
                'path'        => '/RencanaKontrol/ListRencanaKontrol/bulan/{parameter1}/tahun/{parameter2}/nokartu/{parameter3}/filter/{parameter4}',
                'description' => 'Data Rencana Kontrol By No Kartu',
                'params'      => [
                    ['name' => 'parameter1', 'type' => 'text', 'placeholder' => 'Bulan (01-12)', 'default' => ''],
                    ['name' => 'parameter2', 'type' => 'text', 'placeholder' => 'Tahun (yyyy)', 'default' => ''],
                    ['name' => 'parameter3', 'type' => 'text', 'placeholder' => 'Nomor Kartu', 'default' => ''],
                    ['name' => 'parameter4', 'type' => 'text', 'placeholder' => 'Filter (1: tanggal entri, 2: tanggal rencana kontrol)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_rencana_kontrol_list_tanggal',
                'label'       => 'List Rencana Kontrol by Tanggal',
                'method'      => 'GET',
                'path'        => '/RencanaKontrol/ListRencanaKontrol/tglAwal/{parameter1}/tglAkhir/{parameter2}/filter/{parameter3}',
                'description' => 'Data Rencana Kontrol',
                'params'      => [
                    ['name' => 'parameter1', 'type' => 'text', 'placeholder' => 'Tanggal Awal (yyyy-MM-dd)', 'default' => ''],
                    ['name' => 'parameter2', 'type' => 'text', 'placeholder' => 'Tanggal Akhir (yyyy-MM-dd)', 'default' => ''],
                    ['name' => 'parameter3', 'type' => 'text', 'placeholder' => 'Filter (1: tanggal entri, 2: tanggal rencana kontrol)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_rencana_kontrol_spesialistik',
                'label'       => 'List Spesialistik',
                'method'      => 'GET',
                'path'        => '/RencanaKontrol/ListSpesialistik/JnsKontrol/{parameter1}/nomor/{parameter2}/TglRencanaKontrol/{parameter3}',
                'description' => 'Data Rencana Kontrol',
                'params'      => [
                    ['name' => 'parameter1', 'type' => 'text', 'placeholder' => 'Jenis kontrol (1: SPRI, 2: Rencana Kontrol)', 'default' => ''],
                    ['name' => 'parameter2', 'type' => 'text', 'placeholder' => 'Nomor (kartu atau SEP)', 'default' => ''],
                    ['name' => 'parameter3', 'type' => 'text', 'placeholder' => 'Tanggal rencana kontrol (yyyy-MM-dd)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_rencana_kontrol_dokter',
                'label'       => 'Jadwal Dokter',
                'method'      => 'GET',
                'path'        => '/RencanaKontrol/JadwalPraktekDokter/JnsKontrol/{parameter1}/KdPoli/{parameter2}/TglRencanaKontrol/{parameter3}',
                'description' => 'Data Rencana Kontrol',
                'params'      => [
                    ['name' => 'parameter1', 'type' => 'text', 'placeholder' => 'Jenis kontrol (1: SPRI, 2: Rencana Kontrol)', 'default' => ''],
                    ['name' => 'parameter2', 'type' => 'text', 'placeholder' => 'Kode poli', 'default' => ''],
                    ['name' => 'parameter3', 'type' => 'text', 'placeholder' => 'Tanggal rencana kontrol (yyyy-MM-dd)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_fingerprint',
                'label'       => 'Get Finger Print',
                'method'      => 'GET',
                'path'        => '/SEP/FingerPrint/Peserta/{parameter1}/TglPelayanan/{parameter2}',
                'description' => 'Get Finger Print',
                'params'      => [
                    ['name' => 'parameter1', 'type' => 'text', 'placeholder' => 'Nomor Kartu', 'default' => ''],
                    ['name' => 'parameter2', 'type' => 'text', 'placeholder' => 'Tanggal Pelayanan (yyyy-MM-dd)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_fingerprint_list',
                'label'       => 'Get List Finger Print',
                'method'      => 'GET',
                'path'        => '/SEP/FingerPrint/List/Peserta/TglPelayanan/{parameter}',
                'description' => 'Get List Finger Print',
                'params'      => [
                    ['name' => 'parameter', 'type' => 'text', 'placeholder' => 'Nomor Kartu/Tanggal (format: nomorkartu|tanggal)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_fingerprint_random',
                'label'       => 'Get Random Question',
                'method'      => 'GET',
                'path'        => '/SEP/FingerPrint/randomquestion/faskesterdaftar/nokapst/{parameter1}/tglsep/{parameter2}',
                'description' => 'Get Random Question',
                'params'      => [
                    ['name' => 'parameter1', 'type' => 'text', 'placeholder' => 'No Kapst', 'default' => ''],
                    ['name' => 'parameter2', 'type' => 'text', 'placeholder' => 'Tanggal SEP (yyyy-MM-dd)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_fingerprint_answer',
                'label'       => 'Post Random Answer',
                'method'      => 'POST',
                'path'        => '/SEP/FingerPrint/randomanswer',
                'description' => 'Post Random Answer',
                'body'        => [
                    ['name' => 'noKartu', 'type' => 'text', 'placeholder' => 'Nomor Kartu', 'default' => ''],
                    ['name' => 'tglSep', 'type' => 'text', 'placeholder' => 'Tanggal SEP (yyyy-MM-dd)', 'default' => ''],
                    ['name' => 'jnsPel', 'type' => 'text', 'placeholder' => 'Jenis pelayanan (1=Inap, 2=Jalan)', 'default' => ''],
                    ['name' => 'jawaban', 'type' => 'text', 'placeholder' => 'Jawaban pertanyaan', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_suplesi',
                'label'       => 'Potensi SEP Suplesi',
                'method'      => 'GET',
                'path'        => '/sep/JasaRaharja/Suplesi/{parameter1}/tglPelayanan/{parameter2}',
                'description' => 'Pencarian data potensi SEP Sebagai Suplesi Jasa Raharja',
                'params'      => [
                    ['name' => 'parameter1', 'type' => 'text', 'placeholder' => 'Nomor Rujukan', 'default' => ''],
                    ['name' => 'parameter2', 'type' => 'text', 'placeholder' => 'Tanggal Pelayanan (yyyy-MM-dd)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_kll_induk',
                'label'       => 'SEP KLL Induk',
                'method'      => 'GET',
                'path'        => '/sep/KllInduk/List/{parameter}',
                'description' => 'Pencarian data SEP Induk Kecelakaan Lalu Lintas',
                'params'      => [
                    ['name' => 'parameter', 'type' => 'text', 'placeholder' => 'Nomor Rujukan', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_pengajuan',
                'label'       => 'Pengajuan SEP',
                'method'      => 'POST',
                'path'        => '/Sep/pengajuanSEP',
                'description' => 'Pengajuan SEP',
                'body'        => [
                    ['name' => 'request', 'type' => 'json', 'placeholder' => 'JSON body pengajuan', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_aproval',
                'label'       => 'Aproval Pengajuan SEP',
                'method'      => 'POST',
                'path'        => '/Sep/aprovalSEP',
                'description' => 'Aproval Pengajuan SEP',
                'body'        => [
                    ['name' => 'request', 'type' => 'json', 'placeholder' => 'JSON body aproval', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_persetujuan_list',
                'label'       => 'List Data Persetujuan SEP',
                'method'      => 'GET',
                'path'        => '/Sep/persetujuanSEP/list/bulan/{parameter1}/tahun/{parameter2}',
                'description' => 'Get List Data Persetujuan SEP',
                'params'      => [
                    ['name' => 'parameter1', 'type' => 'text', 'placeholder' => 'Bulan (01-12)', 'default' => ''],
                    ['name' => 'parameter2', 'type' => 'text', 'placeholder' => 'Tahun (yyyy)', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_updtglplg',
                'label'       => 'Update Tgl Pulang SEP',
                'method'      => 'POST',
                'path'        => '/Sep/updtglplg',
                'description' => 'Update tanggal pulang SEP',
                'body'        => [
                    ['name' => 'noSep', 'type' => 'text', 'placeholder' => 'Nomor SEP', 'default' => ''],
                    ['name' => 'tglPlg', 'type' => 'text', 'placeholder' => 'Tanggal Pulang (yyyy-MM-dd hh:mm:ss)', 'default' => ''],
                    ['name' => 'ppkPelayanan', 'type' => 'text', 'placeholder' => 'PPK Pelayanan SEP', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_updtglplg_20',
                'label'       => 'Update Tgl Pulang SEP 2.0',
                'method'      => 'POST',
                'path'        => '/SEP/2.0/updtglplg',
                'description' => 'Update tanggal pulang SEP 2.0',
                'body'        => [
                    ['name' => 'noSep', 'type' => 'text', 'placeholder' => 'Nomor SEP', 'default' => ''],
                    ['name' => 'tglPulang', 'type' => 'text', 'placeholder' => 'Tanggal Pulang (yyyy-MM-dd)', 'default' => ''],
                    ['name' => 'noLPManual', 'type' => 'text', 'placeholder' => 'Diisi jika SEPnya adalah KLL', 'default' => ''],
                    ['name' => 'user', 'type' => 'text', 'placeholder' => 'User', 'default' => ''],
                ],
            ],
            [
                'key'         => 'sep_cbg',
                'label'       => 'SEP & Inacbg',
                'method'      => 'GET',
                'path'        => '/sep/cbg/{parameter}',
                'description' => 'Pencarian No.SEP untuk Aplikasi Inacbg 4.1',
                'params'      => [
                    ['name' => 'parameter', 'type' => 'text', 'placeholder' => 'Nomor SEP (19 digit)', 'default' => ''],
                ],
            ],
        ],
    ];